### ISSUE TITLE
Feature request: could you please consider adding OpenCL 1.1 support

### ISSUE THREAD

**Issue by sivagnanamn** [hughperkins/Coriander-CLBlast#1]
Many of the legacy Snapdragon processors support only OpenCL 1.1. Legacy processors needs optimized library more than modern processors with high spec. Please consider providing OpenCL 1.1 support.

**Comment by hughperkins** [comment]
Hi, I dont have time to look into this myself right now. However, I'd be open to pull requests for this, as long as it doesnt disrupt the main code too much. I dont think there are too many OpenCL 1.2 functions being used, but that's something you would need to check.

**Comment by sivagnanamn** [comment]
@hughperkins  Thanks for the awesome library anyways. Will check it.
