### ISSUE TITLE
CUBLAS_OP_Y ??

### ISSUE THREAD

**Issue by iame6162013** [hughperkins/Coriander-CLBlast#2]
I think you made a mistake here: https://github.com/hughperkins/coriander-CLBlast/blob/master/src/cocl_blas.cpp#L67. 

Unless I'm wrong (I could be), CUBLAS_OP_Y doesn't exist. (google shows me 2 results, both within this project)

CUBLAS_OP_Y should be CUBLAS_OP_T (The T of transpose)

line https://github.com/hughperkins/coriander-CLBlast/blob/master/src/cocl_blas.cpp#L69
CUBLAS_OP_T should be CUBLAS_OP_C (the C of conjugate (transpose) )

If you want me to I'll pr the changes.

**Comment by hughperkins** [comment]
Please be very careful not to use eg NVIDIA® documentation to decide on what the api should be.

The *only* evidence we should use when deciding how to define the api should be:

- look at the source-code, of opensource projects, that are running on NVIDIA® CUDA™, and that we want to run instead on OpenCL ,for compatibility purposes
- self-consistency within our own code
- ensuring that our code can build and link with said opensource project code

The existence or not of a particular name on Google is _not_ admissable evidence, unless if falls within the above narrow criteria.

**Comment by hughperkins** [comment]
(so eg, I'm using https://github.com/tbennun/cudnn-training as evidence : an opensource project, that runs on CUDA, and that we want to run on OpenCL, for compatibility purposes )

**Comment by hughperkins** [comment]
(Just to be clear, the reasons I strongly prefer to use the above guidelines is to reduce the 'attack surface' of things which we could be accused of having copied from NVIDIA, and which are not covered by fair use, or similar (compatibility etc).  I think it's fairly straightforward to make a case of using evidence required for compatibility purposes. Simply using particular names and definitions because NVIDIA have a manual that states those seems to me to go above and beyond the need for compatibility, and is less obviously easy to defend, I reckon. I'm not a lawyer, but I think: let's minimize the possible attack surface?)

**Comment by iame6162013** [comment]
> look at the source-code, of opensource projects, that are running on NVIDIA® CUDA™, and that we want to run instead on OpenCL ,for compatibility purposes

Ok, so if I were to look at at an open-source repo, with the goal to better the compatibility of this project with other projects, which has some documentation about NVIDIA® CUDA™ e.g. functions, macros, etc, this would be deemed useful and allowable to be used, by you, for devolvement purposes? Could you state if this is correct?

Remember that minimizing attack surface isn't always enough, if a company were to challenge you in court, legal fees could be high. 
But Wine Is Not an Emulator is still around, so I don't expect this to happen.

**Comment by iame6162013** [comment]
Could you craft a document which states, in rigorous language, what you do and do not deem as an acceptable source? 

I'd prefer, because if/when coriander gets more developers they should/need to be informed about what is and isn't allowed, that the following things would be addressed:

- Is code and documentation from e.g. https://stackoverflow.com/ allowable to increase the sample size and diversity of programs and/or source code to further the compatibility of coriander and it's plugins? 

- Are example programs written, by third-parties e.g. google, in NVIDIA® CUDA™  allowable as a source? 

- Is the above allowable if NVIDIA created and or distributed these example?

- Does a source need to be stated when someone contributes code to the project?

**Comment by iame6162013** [comment]
Is this what you want? https://wiki.winehq.org/Clean_Room_Guidelines

>  But play it safe - if a test program will do, don't look at any Microsoft doc or headers.

Do you want to forbid looking at the doc and headers, which is not explicitly forbidden by wine? 

(If you smell/sense any opinion, there is none intended. )

**Comment by hughperkins** [comment]
I disagree that it's ok to look at NVIDIA headers at all. Theres really no need. There are only two possibilities:
- 1. by looking at a program that uses CUDA, you can deduce the exact same type as NVIDIA used. in which case there's no need to look at their headers
- 2. by looking at a program that uses CUDA, you can narrow down a type to one of several possible candidates, but cannot disambiguate them. In which case, all of them will work, just pick an arbitrary one
   - in addition, I tend to chose the *least* likely looking one, that is sufficient for the client program to work
   - for example, I give all the enums really strange constants, like `34233`, and stuff, stuff extremely unlikely to match what is really in fact in the headers

docs is more of a grey area. doc which says what stuff conceptually ... is not necessarily something I avoid personally. doc about the specific api call types and stuff, is information we can get from looking at client program code, so let's just get it from looking at client program code instead? (albeit it's a ~~bit~~ tons more work :( ).

But yes, the page you've found is highly aligned with how I see this, and with the problem we are trying to solve here, ie not just gratuitously copy stuff across, except for the strict purposes of compatibility.

**Comment by hughperkins** [comment]
By the way, an extremely relevant case, which sort of oscillates back and forth is: 

- http://www.businessinsider.com/google-oracle-lawsuit-is-damaging-2014-5?IR=T
- https://arstechnica.com/tech-policy/2016/05/google-wins-trial-against-oracle-as-jury-finds-android-is-fair-use/

But, on the whole, I think the best guidelines I found on what is/isnt allowed, that I tend to follow personally, is, well I cant find it, but it was something like, whoever has the most money/influence tends to win legal cases. But, this involves not just the specific people/companies in the case, but other people around, and companies. Basically, the courts on the whole try not to do things that people/companies will think too outrageous.  It's a grey area, not a black and white thing.  Hence, copy the least possible, even if it involves more work. At the most basic level, it means when/if other people do look, they can see that we are doing due diligence in copying the least possible, even though it involves more work.

**Comment by iame6162013** [comment]
>  doc about the specific api call types and stuff, is information we can get from looking at client program code, so let's just get it from looking at client program code instead?

You seem to stress "client program code", do you want to exclude documentation ~of~ in the  client program
e.g.
> CUBLAS_OP_T specifies xyz

And possibly wrappers? 
Since it isn't really 'code' or a program, but wrappers do have documentation, thus being of high value to us, no?

(closing it was an accident, sorry.)

**Comment by hughperkins** [comment]
> do you want to exclude documentation of in the client program

So, if someone has embedded documentation about the NVIDIA API in their own program's documentation, then we cant just claim 'oh, we werent reading NVIDIA's documentaiton! We just read the doc in the program!'. We should only look at the minimum of NVIDIA-colored things as possible, in order to provide compatibility for the non-NVIDIA, opensource, CUDA-using program.

What do I mean by 'color'? it's not really a technical term, but this article invents the term, and I think the article is quite nice: http://ansuz.sooke.bc.ca/entry/23

**Comment by iame6162013** [comment]
Ok, I can see why prohibiting reading doc inside program makes some sense, but doesn't the doc written by NVIDIA only have copyright protecting it? Ignoring the latter for safety is a wise move.

Just one question, you say that we should look at as few NVIDIA colored things as possible, we may not look at a non derivative documents(may be integrated in the source code) documenting the NVIDIA API written by third parties but we may look at non derivative source code written by third parties? 

How do the above have a different colour? One gives you an example, the other gives you a definition, both are (probably) written with the NVIDIA documentation on hand. Neither may include quotations from NVIDIA documentation or risk being labeled derivative work nor may they plagiarize.

Thus we're no longer protecting ourselves from NVIDIA, they don't own the rights to the works in question, we're not reducing the attack surface, AFAIK they have no legal/moral(?) support to attack in this direction.

If my statement above is non convincing, what about a research paper having conducted a test between the processing speed(e.g.Cholesky) of NVIDIA CUDA vs opencl? May we not look at papers like these? 

(I think it goes without saying, I'm not a lawyer)

**Comment by iame6162013** [comment]
Confirming whether I'm correct about CUBLAS_OP_T being 'miss implemented' in this plugin should be simple, since you stated:
> [...] doc about the specific api call types and stuff, is information we can get from looking at client program code [...]

Since you only implemented functions for floats (no complex values, used https://github.com/CNugteren/CLBlast/blob/master/doc/clblast.md to confirm this) we'd only need to check if https://github.com/tbennun/cudnn-training uses CUBLAS_OP_Y or CUBLAS_OP_T.

There are 2 ways to get to know this:

1. Log this plugin when running cudnn-training
Pros: Legally the safest
Cons: Productivity wise the slowest
2. Reading the "client program code"
Pros: Productivity wise the fastest
Cons: Possibly a larger attack surface

Both would be allowed by what you've stated, after you've stated if you agree with the testing methodology (any of the 2 would do) I'll test it.

**Comment by hughperkins** [comment]
reading the code in cudnn-training repo seems fine to me.

**Comment by iame6162013** [comment]
Cudnn-training uses CUBLAS_OP_T on a float*, the float* doesn't have space to implement complex values, thus 'CUBLAS_OP_T' probably implies a regular transpose not a conjugate transpose. 

Since I can't find anything related to CUBLAS_OP_Y, I'll assume it doesn't need to exist.

I'll make a pr to reflect the findings above (and test the changes) .
