### ISSUE TITLE
cublas (type) getrfBatched unimplemented.

### ISSUE THREAD

**Issue by iame6162013** [hughperkins/Coriander-CLBlast#4]
Tensorflow currently uses this function, thus it would be a good idea to implement it.
Sadly CLBlast doesn't support getrf nor getrfBatched.

I haven't yet found a smaller project that uses the function (cublas (type) getrfBatched) with a license (other than implied exclusive copyright).

**Comment by iame6162013** [comment]
The following MIT licensed project does use the function in python https://github.com/benanne/wmf

**Comment by hughperkins** [comment]
Interesting. I think that matrix factorization is very similar to a net? eg googling quickly throws up https://github.com/jstol/neural-net-matrix-factorization , but searching eg for 'word2vec matrix factorization' throws up for example https://papers.nips.cc/paper/5477-neural-word-embedding-as-implicit-matrix-factorization and https://www.reddit.com/r/MachineLearning/comments/2m34kp/word2vec_is_actually_just_matrix_factorization/

**Comment by iame6162013** [comment]
Should this function be implemented in this plugin, or should lapack functions be implemented in it's own separate plugin?

Pros for separation:
- Better separation of lapack and blas functions.
- Clblast won't be implementing getrfBatched thus requiring either a new implementation here or a different lib, the latter causing this lib to be a misnomer.

Cons:
- Harder for the end user to see which plugins (s)he needs.
